<a href="https://colab.research.google.com/github/allen-del/Learning_PyTorch/blob/main/00.%20Fundamentals/00pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Learning the basics of Pytorch


<p>Yes, the formatting does get better in the next few notebooks.

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


<h3>What are Tensors?
<p>Simply just a multidimensional array of numbers (representing data)


####Creating tensors

In [ ]:
#scalar
scalar = torch.tensor(1)
scalar

tensor(1)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

1

In [ ]:
#vector
vector = torch.tensor([1,1])
vector

tensor([1, 1])

In [ ]:
vector.ndim


1

In [ ]:
vector.shape


torch.Size([2])

<p> <li>Dimensions(ndim) - count number of square brackets
<p> <li>Shape - from outer to inner

In [ ]:
#MATRIX
MATRIX = torch.tensor([[1,2],[3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[[1,2],[3,4],[5,6],],[[11,12],[13,14],[15,16]]]])
TENSOR

tensor([[[[ 1,  2],
          [ 3,  4],
          [ 5,  6]],

         [[11, 12],
          [13, 14],
          [15, 16]]]])

In [ ]:
TENSOR.ndim

4

In [ ]:
TENSOR.shape

torch.Size([1, 2, 3, 2])

In [ ]:
TENSOR[0]

tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[11, 12],
         [13, 14],
         [15, 16]]])

#####Zero and Empty Tensors

In [ ]:
#tensors intialized with zeros as elements
zero_tensor = torch.zeros(1,2,3)
zero_tensor

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [ ]:
zero_tensor.ndim

3

In [ ]:
zero_tensor.shape

torch.Size([1, 2, 3])

In [ ]:
#Empty tensors

empty_tensor = torch.empty(1,2)
empty_tensor

tensor([[3.2045e-31, 4.5768e-41]])

<p> For empty tensors only memory is allocated

#####Random tensors and Reproducibility

To reduce the generated randomness we can use **random seed** to flavour randomness

In [ ]:
random = torch.rand(2,3,4)
random

tensor([[[0.3870, 0.5463, 0.8028, 0.9109],
         [0.7242, 0.8855, 0.0479, 0.3936],
         [0.9709, 0.3566, 0.3618, 0.8653]],

        [[0.4084, 0.3207, 0.5440, 0.4719],
         [0.3569, 0.6773, 0.0655, 0.9412],
         [0.8703, 0.3457, 0.0424, 0.2824]]])

In [ ]:
random1 = torch.rand(2,3,4)
random1

tensor([[[0.3520, 0.4617, 0.5193, 0.4751],
         [0.0615, 0.3522, 0.0855, 0.7950],
         [0.0042, 0.0321, 0.3942, 0.4632]],

        [[0.8483, 0.5673, 0.0531, 0.2544],
         [0.1366, 0.3231, 0.6628, 0.8954],
         [0.6514, 0.2493, 0.7901, 0.9694]]])

In [ ]:
#If we manually seed then both random tensors generated will have the same value
torch.manual_seed(69)
random2 = torch.rand(1,2,3)
random2

tensor([[[0.8398, 0.8042, 0.1213],
         [0.5309, 0.6646, 0.4077]]])

In [ ]:
torch.manual_seed(69)
random3 = torch.rand(1,2,3)
random3

tensor([[[0.8398, 0.8042, 0.1213],
         [0.5309, 0.6646, 0.4077]]])

In [ ]:
random3.dtype

torch.float32

#####Creating a range of tensors and tensors like (sharing same dimensions)

In [ ]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#You can directly write the arguments also
one_to_five = torch.arange(1,6,1)
one_to_five

tensor([1, 2, 3, 4, 5])

In [ ]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###Tensor datatypes
<p> Mainly float16,32,64 and int32,64(aka Long)

In [ ]:
float_32_tensor = torch.tensor([2.0,1.9,3.0],
                               dtype=None,#Data type of Tensor. Usually float 32(single precision) by default unless specified
                               device=None,#Default is CPU. Operations have to be performed between tensors in the same device ie both in CPU or CUDA
                               requires_grad=False)

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
#changing the type
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [ ]:
result= float_16_tensor*float_32_tensor
result.dtype

torch.float32

In [ ]:
int_32_tensor=torch.tensor([1,2,3],dtype=torch.int32)
int_32_tensor

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
result=float_32_tensor*int_32_tensor
result,result.dtype


(tensor([2.0000, 3.8000, 9.0000]), torch.float32)

In [ ]:
result=int_32_tensor*float_16_tensor
result,result.dtype

(tensor([2.0000, 3.8008, 9.0000], dtype=torch.float16), torch.float16)

In [ ]:
result.device

device(type='cpu')

In [ ]:
#Recap
some_tensor = torch.rand(2,3)
some_tensor.dtype

torch.float32

In [ ]:
some_tensor.type(torch.float16)

tensor([[0.0887, 0.2429, 0.7056],
        [0.6216, 0.9189, 0.0185]], dtype=torch.float16)

In [ ]:
some_tensor.shape

torch.Size([2, 3])

In [ ]:
some_tensor.device

device(type='cpu')

###Manipulating Tensors(Tensor Operations)
<p> Element operations: <ul>
<li> Addition
<li> Subtraction
<li> Division
<li> Multiplication (different from Matrix Multiplication)


In [ ]:
tensor = torch.arange(start=1,end=5,step=1)
tensor, tensor+2, tensor-10, tensor*10, tensor/10

(tensor([1, 2, 3, 4]),
 tensor([3, 4, 5, 6]),
 tensor([-9, -8, -7, -6]),
 tensor([10, 20, 30, 40]),
 tensor([0.1000, 0.2000, 0.3000, 0.4000]))

In [ ]:
torch.mul(tensor, 20),torch.add(tensor,10)

(tensor([20, 40, 60, 80]), tensor([11, 12, 13, 14]))

In [ ]:
%%time
value=0
for i in range (len(tensor)):
  value+=tensor[i]*tensor[i]
value

CPU times: user 303 µs, sys: 0 ns, total: 303 µs
Wall time: 312 µs


tensor(30)

In [ ]:
%%time
torch.matmul(tensor,tensor)
#torch uses vectorization to achieve much faster speeds than manual looping, multiplication and addition

CPU times: user 850 µs, sys: 0 ns, total: 850 µs
Wall time: 812 µs


tensor(30)

####Matrix Multiplication

In [ ]:
#Matrix Multiplication

tensor_A= torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])

print(f"Tensor A's shape: {tensor_A.shape}")
print(f"Tensor B's shape: {tensor_B.shape}")

#`torch.matmul(tensor_A,tensor_B)` will return error because inner dimensions aren't same so Matrix Multiplication not possible

Tensor A's shape: torch.Size([3, 2])
Tensor B's shape: torch.Size([3, 2])


In [ ]:
tensor_C = torch.tensor([[7,8,9],[10,11,12]])
print(f"Tensor C's shape: {tensor_C.shape}")
torch.matmul(tensor_A,tensor_C)

Tensor C's shape: torch.Size([2, 3])


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

<p>If we have to multiply tensors A and B we need to resolve shape error. How do we do it?

####Transpose

In [ ]:
#Transpose switches the dimensions or axes of the given tensor.
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
tensor_B.T.shape

torch.Size([2, 3])

In [ ]:
#Notice that the dimensions are flipped. Now we can matrix multiply.
new_tensor_B = tensor_B.T
torch.matmul(tensor_A,new_tensor_B)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

###Tensor Aggregation

####Finding the min, max, mean, sum etc.

In [ ]:
y= torch.arange(start=0,end=100,step=5)
y

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])

In [ ]:
torch.min(y)

tensor(0)

In [ ]:
torch.max(y)

tensor(95)

In [ ]:
y=y.type(torch.float32)
y.dtype

torch.float32

In [ ]:
print(y.mean())
torch.mean(y)

tensor(47.5000)


tensor(47.5000)

In [ ]:
torch.sum(y)

tensor(950.)

####Finding Positional Min and Max (returns where the element is located)

In [ ]:
random_tensor = torch.rand(3,10)
random_tensor

tensor([[0.2830, 0.8929, 0.5384, 0.0219, 0.0473, 0.8484, 0.8749, 0.1102, 0.4257,
         0.3868],
        [0.1889, 0.4410, 0.0286, 0.5514, 0.8156, 0.5011, 0.7597, 0.6858, 0.3605,
         0.3658],
        [0.9362, 0.0408, 0.6278, 0.1817, 0.7110, 0.2446, 0.1089, 0.3925, 0.9651,
         0.8191]])

In [ ]:
random_tensor = (random_tensor*100).type(torch.int32)
random_tensor

tensor([[67, 38, 24, 82, 87, 63, 38,  4, 84, 79],
        [91, 13, 19, 64, 13, 81, 83, 89,  4, 17],
        [88, 87, 74, 32, 97, 74, 99, 44, 17, 88]], dtype=torch.int32)

In [ ]:
torch.argmax(random_tensor)

tensor(26)

In [ ]:
torch.argmin(random_tensor)

tensor(7)

###Reshaping, stacking , squeezing and unsqueezing tensors + Permute

* Reshaping- reshapes input tensor to a defined shape

* View - Returns view of some input tensor of a certain shape but keeps same memory as original tensor

* Stacking - combining multiple tensors on top of each other or side by side.
* Squeeze- removes all `1` dimension from a tensor
* Unsqueeze- adds a `1` dimsion to a tensor
* Permute- Return a view of the input with dimensions permuted (swapped) in some given way.

In [ ]:
import torch
x = torch.arange(1,10,1)
x,x.shape


(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
#Reshape by adding an extra dimension. The dimensions have to be compatible.
x_reshaped = x.reshape(1,7)
x,x_reshaped #Error because we have 9 (1*9) elements to fill 7 (1*7) places

RuntimeError: shape '[1, 7]' is invalid for input of size 9

In [ ]:
x_reshaped = x.reshape(1,9)
x,x_reshaped

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]))

In [ ]:
x_reshaped = x.reshape(9,1)
x, x_reshaped

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]))

In [ ]:
x_reshaped = x.reshape(1,9,1)
x,x_reshaped

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([[[1],
          [2],
          [3],
          [4],
          [5],
          [6],
          [7],
          [8],
          [9]]]))

In [ ]:
#Change view
z = x.view(1,9)
z, z.shape #similar to reshape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
#Changing z(view) changes x (because view of tensor shares same memory)
z[:,0] = 101 #Slicing tensor into sub arrays[dim1,dim2 ...] dimensions can be specified as start:end+1
z,x

(tensor([[101,   2,   3,   4,   5,   6,   7,   8,   9]]),
 tensor([101,   2,   3,   4,   5,   6,   7,   8,   9]))

In [ ]:
#Stacking Tensors on top of each other
x_stacked = torch.stack([x,x,x],dim = 0)
x,x_stacked

tensor([[101,   2,   3,   4,   5,   6,   7,   8,   9],
        [101,   2,   3,   4,   5,   6,   7,   8,   9],
        [101,   2,   3,   4,   5,   6,   7,   8,   9]])

In [ ]:
x_stacked = torch.stack([x,x,x],dim = 1)
x,x_stacked

(tensor([101,   2,   3,   4,   5,   6,   7,   8,   9]),
 tensor([[101, 101, 101],
         [  2,   2,   2],
         [  3,   3,   3],
         [  4,   4,   4],
         [  5,   5,   5],
         [  6,   6,   6],
         [  7,   7,   7],
         [  8,   8,   8],
         [  9,   9,   9]]))

<p>Notice how setting `dim = 0` is for vstack ie, stacking row by row and setting `dim = 1` is for hstack ie, columnwise stacking.

In [ ]:
#Squeezing
x_squeezed = torch.squeeze(x_reshaped, dim=(0,2))
x_reshaped,x_squeezed

(tensor([[[101],
          [  2],
          [  3],
          [  4],
          [  5],
          [  6],
          [  7],
          [  8],
          [  9]]]),
 tensor([101,   2,   3,   4,   5,   6,   7,   8,   9]))

In [ ]:
x_reshaped.shape,x_squeezed.shape

(torch.Size([1, 9, 1]), torch.Size([9]))

In [ ]:
#Unsqueezing
x_unsqueezed= torch.unsqueeze(x_squeezed,dim=0)
x_unsqueezed

tensor([[101,   2,   3,   4,   5,   6,   7,   8,   9]])

In [ ]:
x_unsqueezed.shape

torch.Size([1, 9])

In [ ]:
#torch.permute - to rearrange dimensions in a specific order. Commonly used for image processing

a_original = torch.rand(224,224,3) #[height, width, color_channels]

#Suppose we need it in the order [color_channels, height, width]

a_permuted = a_original.permute(2,0,1) #shifts axis or dim

a_original.shape,a_permuted.shape


(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

<p> Note: `torch.permute` returns a view so any changes to the new tensor will reflect on the old one as well

In [ ]:
a_original[0,0,0]=69

In [ ]:
a_permuted[0,0,0]

tensor(69.)

###Indexing (Selecting Data from Tensors)

In [ ]:
import torch
x = torch.arange(1,10).reshape(1,3,3)

In [ ]:
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0,0]

tensor([1, 2, 3])

In [ ]:
x[0,0,0]

tensor(1)

In [ ]:
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
x[0,:,1]

tensor([2, 5, 8])

In [ ]:
x[0,2,2]

tensor(9)

In [ ]:
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
x[:,:,2]

tensor([[3, 6, 9]])

##PyTorch and NumPy

* Data in Numpy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`

* Data in PyTorch tensor to NumPy -> `Tensor.numpy()`

In [ ]:
import torch
import numpy as np

array = np.arange(1.0,20.0,2.0)
tensor = torch.from_numpy(array)
array, tensor, tensor.shape

(array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.]),
 tensor([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.], dtype=torch.float64),
 torch.Size([10]))

In [ ]:
tensor = torch.ones(7)
numpy_array = tensor.numpy()
numpy_array

array([1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [ ]:
tensor = torch.ones(8)
tensor1 = torch.zeros(8)
tensor_stacked= torch.stack([tensor,tensor1], dim=1)
tensor_stacked

tensor([[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]])

In [ ]:
numpy_array = tensor_stacked.numpy()
numpy_array

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.]], dtype=float32)

##Using GPUs

GPUs are faster for numerical computations than CPU because CUDA+ NVIDIA Hardware + PyTorch

1. Check in bash what GPU is being used
2. Check for GPU access with PyTorch code and set up to use

In [ ]:
!nvidia-smi

Mon May  6 19:57:37 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   35C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
#using PyTorch

import torch

torch.cuda.is_available() # Returns true if we're using GPU supporting CUDA

True

In [ ]:
#Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"

In [ ]:
#Count number of devices
torch.cuda.device_count()

1

In [ ]:
#Moving Tensor to GPU

x = torch.tensor([1,2,3])
x.device


device(type='cpu')

In [ ]:
x_on_gpu = x.to(device)
x_on_gpu

tensor([1, 2, 3], device='cuda:0')

<p>Numpy only works on CPU. How might we move back tensor to GPU?

In [ ]:
x_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
x_back_on_cpu = x_on_gpu.cpu()

In [ ]:
x_back_on_cpu.device



device(type='cpu')

In [ ]:
x_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

#RECAP and Practice

In [ ]:
import torch
import numpy as np
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(f"The Data type of created tensor is: {x.dtype} \nThe Shape is: {x.shape} \nThe number of dimensions: {x.ndim}")

The Data type of created tensor is: torch.int64 
The Shape is: torch.Size([3, 3]) 
The number of dimensions: 2


In [ ]:
x_zeros=torch.zeros(2,3)
x_zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
x_ones=torch.ones(1,2,3)
x_ones

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [ ]:
x_random=torch.rand(1,2)
x_random

tensor([[0.6487, 0.8345]])

In [ ]:
torch.manual_seed(42)
x_random1=torch.rand(1,2)
x_random1

tensor([[0.8823, 0.9150]])

In [ ]:
torch.manual_seed(42)
x_random2=torch.rand(1,2)
x_random2

tensor([[0.8823, 0.9150]])

In [ ]:
x=torch.arange(1,11,1)
x,x.dtype

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.int64)

In [ ]:
x=x.type(torch.int32)
x.dtype

torch.int32

In [ ]:
y=torch.zeros_like(x)
y

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.int32)

In [ ]:
z=torch.ones_like(x)
z

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=torch.int32)

In [ ]:
a=torch.stack([x,y,z],dim=0)
a

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1]], dtype=torch.int32)

In [ ]:
a.ndim

2

In [ ]:
a.T, a

(tensor([[ 1,  0,  1],
         [ 2,  0,  1],
         [ 3,  0,  1],
         [ 4,  0,  1],
         [ 5,  0,  1],
         [ 6,  0,  1],
         [ 7,  0,  1],
         [ 8,  0,  1],
         [ 9,  0,  1],
         [10,  0,  1]], dtype=torch.int32),
 tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
         [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
         [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1]], dtype=torch.int32))

In [ ]:
print(f"The max element is {torch.max(a)} and its position is {torch.argmax(a)}")

The max element is 10 and its position is 9


In [ ]:
print(f"The min element in {x_random} is {torch.min(x_random)} and its position is {torch.argmin(x_random)}")

The min element in tensor([[0.6487, 0.8345]])nt is 0.6486715078353882 and its position is 0


In [ ]:
torch.mean(x_random), torch.sum(x_random)

(tensor(0.7416), tensor(1.4832))

In [ ]:
x = torch.arange(1.0,11.0)
x,x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
y=x.reshape(1,1,10)
y,y.shape

(tensor([[[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]]),
 torch.Size([1, 1, 10]))

In [ ]:
z=y.view(1,10,1)
z

tensor([[[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]])

In [ ]:
y[:,:,8]=42
y,z

(tensor([[[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8., 42., 10.]]]),
 tensor([[[ 1.],
          [ 2.],
          [ 3.],
          [ 4.],
          [ 5.],
          [ 6.],
          [ 7.],
          [ 8.],
          [42.],
          [10.]]]))

In [ ]:
z_new=z.squeeze(dim=[0,2])
z_new.shape

torch.Size([10])

In [ ]:
z_unsq=z_new.unsqueeze(dim=0)

In [ ]:
z_unsq.shape

torch.Size([1, 10])

In [ ]:
x=torch.rand(128,720,3)

In [ ]:
x_permuted=x.permute(2,0,1)

In [ ]:
x_permuted.shape

torch.Size([3, 128, 720])