<a href="https://colab.research.google.com/github/allen-del/Learning_PyTorch/blob/main/00.%20Fundamentals/pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Exercises from https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises

###Tasks 1, 2, 3, 4

In [ ]:
import torch
import numpy as np
torch.manual_seed(0)
x = torch.rand(7,7)
x.shape


torch.Size([7, 7])

In [ ]:
torch.manual_seed(0)
y = torch.rand(1,7)
y_new=y.T
z=torch.matmul(x,y_new)
print(f"Tensor X:\n{x,x.shape} @ \n Tensor Y(Transposed for Matrix Multiplication):\n{y_new,y_new.shape}\n = Tensor Z:\n{z,z.shape} ")

Tensor X:
(tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]), torch.Size([7, 7])) @ 
 Tensor Y(Transposed for Matrix Multiplication):
(tensor([[0.4963],
        [0.7682],
        [0.0885],
        [0.1320],
        [0.3074],
        [0.6341],
        [0.4901]]), torch.Size([7, 1]))
 = Tensor Z:
(tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]]), torch.Size([7, 1])) 


###Task 5

Manual seed using GPU

In [ ]:
import torch
import numpy as np
torch.cuda.is_available()

True

In [ ]:

torch.cuda.manual_seed(1234)
x = torch.rand(7,7)
x.shape


torch.Size([7, 7])

In [ ]:
torch.manual_seed(1234)
y = torch.rand(1,7)
y_new=y.T
z=torch.matmul(x,y_new)
print(f"Tensor X:\n{x,x.shape} @ \n Tensor Y(Transposed for Matrix Multiplication):\n{y_new,y_new.shape}\n = Tensor Z:\n{z,z.shape} ")

Tensor X:
(tensor([[0.6189, 0.5405, 0.3721, 0.2509, 0.6870, 0.7888, 0.1317],
        [0.0399, 0.1904, 0.5136, 0.0348, 0.9489, 0.4304, 0.4897],
        [0.5049, 0.8215, 0.9686, 0.2528, 0.1364, 0.8796, 0.1286],
        [0.8067, 0.2194, 0.4839, 0.6541, 0.3686, 0.0572, 0.5168],
        [0.4256, 0.9074, 0.1842, 0.7048, 0.4049, 0.6440, 0.3135],
        [0.6286, 0.8647, 0.6968, 0.3007, 0.5033, 0.0713, 0.0483],
        [0.3431, 0.0511, 0.5384, 0.0486, 0.7380, 0.9788, 0.7314]]), torch.Size([7, 7])) @ 
 Tensor Y(Transposed for Matrix Multiplication):
(tensor([[0.0290],
        [0.4019],
        [0.2598],
        [0.3666],
        [0.0583],
        [0.7006],
        [0.0518]]), torch.Size([7, 1]))
 = Tensor Z:
(tensor([[1.0234],
        [0.6061],
        [1.3201],
        [0.5654],
        [1.1743],
        [0.7389],
        [0.9549]]), torch.Size([7, 1])) 


###Task 6, 7, 8, 9

In [ ]:
torch.manual_seed(1234)
a = torch.rand(2,3)
torch.manual_seed(1234)
b = torch.rand_like(a)
a,b

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]))

In [ ]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
a.device,b.device

(device(type='cpu'), device(type='cpu'))

In [ ]:
a_on_gpu=a.to(device)
b_on_gpu=b.to(device)

In [ ]:
a_on_gpu.device, b_on_gpu.device

(device(type='cuda', index=0), device(type='cuda', index=0))

In [ ]:
%%time
z=torch.matmul(a_on_gpu,b_on_gpu.T)

CPU times: user 1.19 ms, sys: 0 ns, total: 1.19 ms
Wall time: 1.21 ms


In [ ]:
%%time
torch.matmul(a,b.T)

CPU times: user 114 µs, sys: 6 µs, total: 120 µs
Wall time: 126 µs


tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]])

In [ ]:
z.max(),z.min()

(tensor(0.6287, device='cuda:0'), tensor(0.2161, device='cuda:0'))

In [ ]:
z.argmax(),z.argmin()

(tensor(3, device='cuda:0'), tensor(1, device='cuda:0'))

### Task 10

In [ ]:
torch.manual_seed(7)
x = torch.rand(1,1,1,10)
y = x.squeeze()
print(f"Tensor X: \n{x,x.shape} \n Tensor Y: \n{y,y.shape}")

Tensor X: 
(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]), torch.Size([1, 1, 1, 10])) 
 Tensor Y: 
(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]), torch.Size([10]))
